### ISSUE TITLE
快速左滑或右滑时，没有出现左视图或者右视图，而是回去了。

### ISSUE THREAD

**Issue by Micheal-Long** [mengxianliang/XLSlideMenu#3]
如题，特意看了下QQ的抽屉效果，当快速滑动时会弹出抽屉来，而XLSlideMenu不会。XLSlideMenu只会是超过了一定宽度后才会出来。为了体验，建议修复下(我还在看怎么修复)。

**Comment by mengxianliang** [comment]
你好，已经兼容了快速滑动，新代码已提交。
