### ISSUE TITLE
建议修复

### ISSUE THREAD

**Issue by biqinglin** [mengxianliang/XLSlideMenu#4]
我看了侧滑层级关系以及相关代码，发现其实你将menuView.frame = 屏幕的尺寸，其实这样是不对的。menu的frame应该等于它展示出来的尺寸，如果你那样写就有一部分视图被遮挡了，也就是布局展示问题。
建议fix

**Comment by biqinglin** [comment]
贴上对比图[image](http://occmuwiio.bkt.clouddn.com/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202017-09-26%20%E4%B8%8B%E5%8D%883.14.26.png)
[image](http://occmuwiio.bkt.clouddn.com/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202017-09-26%20%E4%B8%8B%E5%8D%883.13.28.png)

**Comment by mengxianliang** [comment]
已经修复了，谢谢你的建议。

**Comment by biqinglin** [comment]
互勉
