### ISSUE TITLE
写的很好楼主，星星已送出，但是有一个问题

### ISSUE THREAD

**Issue by 19933139420** [mengxianliang/XLSlideMenu#5]
楼主，如果rootViewController是tabbarController的时候，底部的tabbar是不会被_coverView覆盖上的，所以我在您的XLSlideMenu 的-viewDidLoad：方法中国年添加了[_rootViewController.view bringSubviewToFront:_coverView]; 来实现tabbarController底部tabbar的遮盖

**Comment by mengxianliang** [comment]
已经优化了，谢谢你的建议。
