### ISSUE TITLE
可以用于有tabbar的app吗？

### ISSUE THREAD

**Issue by KONGFANJI** [mengxianliang/XLSlideMenu#6]
app有4个tabbar，在第一个tabbar使用这种效果可以吗？

**Comment by mengxianliang** [comment]
你好，这个是可以用于有tabbar的app的。
你说app里有四个tabbar，我可以理解成app里有一个tabbar，tabbar里有四个自控制器吧。
如果想在第一个自控制器里使用滑动菜单，其他控制器里不实用，需要在自控制器里动态设定滑动开关的属性self.xl_sldeMenu.slideEnabled

**Comment by KONGFANJI** [comment]
谢谢你的回复，是你理解的意思。我想问一下，有类似的demo吗，我把XLSlideMenu加载了第一个导航栏里，可以侧滑，但是push的时候不能隐藏tabbar，搞不清楚什么原因，还请赐教，谢谢啦
